<?php

/**
 * @file
 * Functions to support theming in the localgov_theme_croydon theme.
 */

/**
 * Implements hook_preprocess_page() for hook_preprocess_page__localgov_guides_overview().
 *
 * - Content region always occupies 8 out of 12 columns in wider displays.
 */
function localgov_theme_croydon_preprocess_page__localgov_guides_overview(&$variables) {

  $variables['has_sidebar_second'] = TRUE;
}

/**
 * Implements hook_preprocess_page() for hook_preprocess_page__localgov_guides_page().
 *
 * - Content region always occupies 8 out of 12 columns in wider displays.
 */
function localgov_theme_croydon_preprocess_page__localgov_guides_page(&$variables) {

  $variables['has_sidebar_second'] = TRUE;
}

/**
 * Implements hook_preprocess_page() for hook_preprocess_page__localgov_step_by_step_overview().
 *
 * - Content region always occupies 8 out of 12 columns in wider displays.
 */
function localgov_theme_croydon_preprocess_page__localgov_step_by_step_overview(&$variables) {

  $variables['has_sidebar_second'] = TRUE;
}

/**
 * Implements hook_preprocess_page() for hook_preprocess_page__localgov_services_page().
 *
 * - Content region always occupies 8 out of 12 columns in wider displays.
 */
function localgov_theme_croydon_preprocess_page__localgov_services_page(&$variables) {

  $variables['has_sidebar_second'] = TRUE;
}
